/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#1b1b1b',
        secondary: '#755b00',
        background: '#f9f9f9',
        tertiary: '#006a62',
        'on-primary-fixed-variant': '#7b1c70',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#ffacea',
        surface: '#f9f9f9',
        'on-tertiary-fixed': '#00201d',
        'surface-dim': '#dadada',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'bg-primary': '#FFFDF8',
        'tertiary-fixed': '#87f5e7',
        'surface-container-low': '#f3f3f3',
        'inverse-on-surface': '#f1f1f1',
        'text-primary': '#000000',
        'on-secondary-fixed-variant': '#584400',
        'inverse-primary': '#ffacea',
        'on-tertiary-container': '#00514a',
        'on-surface': '#1b1b1b',
        'surface-container-high': '#e8e8e8',
        'secondary-fixed': '#ffdf91',
        outline: '#84727d',
        'surface-bright': '#f9f9f9',
        'on-secondary-fixed': '#241a00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdc800',
        'bg-secondary': '#FFFFFF',
        'on-secondary-container': '#6d5500',
        'on-tertiary-fixed-variant': '#005049',
        'surface-tint': '#983789',
        'tertiary-fixed-dim': '#69d8cb',
        'on-surface-variant': '#52424c',
        'surface-variant': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        primary: '#983789',
        'on-primary-container': '#7c1d71',
        'primary-fixed': '#ffd7f1',
        'tertiary-container': '#58c8bb',
        'outline-variant': '#d6c1cd',
        'surface-container': '#eeeeee',
        'secondary-fixed-dim': '#f3c000',
        'on-primary-fixed': '#390034',
        'surface-container-highest': '#e2e2e2',
        error: '#ba1a1a',
        'primary-container': '#ff90e8',
        'on-error-container': '#93000a',
        'inverse-surface': '#303030',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        none: '0px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'shadow-offset': '6px',
        'border-width': '4px',
        'shadow-offset-pressed': '2px',
      },
      // Tailwind's translate/inset/margin utilities alias to the spacing
      // scale by default, but borderWidth does not — so it needs its own
      // entry for classes like `border-border-width` / `border-b-border-width`
      // (used throughout the components) to actually generate CSS.
      borderWidth: {
        DEFAULT: '1px',
        0: '0px',
        2: '2px',
        4: '4px',
        8: '8px',
        'border-width': '4px',
      },
      fontFamily: {
        'headline-lg': ['Space Grotesk'],
        'label-mono': ['Space Mono'],
        'body-lg': ['Public Sans'],
        'headline-md': ['Space Grotesk'],
        'body-md': ['Public Sans'],
        'headline-lg-mobile': ['Space Grotesk'],
        'headline-sm': ['Space Grotesk'],
      },
      fontSize: {
        'headline-lg': ['64px', { lineHeight: '1.1', fontWeight: '900' }],
        'label-mono': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['22px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['40px', { lineHeight: '1.2', fontWeight: '800' }],
        'body-md': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
        'headline-lg-mobile': ['40px', { lineHeight: '1.1', fontWeight: '900' }],
        'headline-sm': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
